import Newspeak.Id

namespace Newspeak

inductive Access where
  | publicAccess
  | protectedAccess
  | privateAccess
deriving Repr, DecidableEq, BEq

inductive ClassBodyDecl where
  | namedClass (decl : ClassDeclId)
  | objectLiteral (decl : ObjectLiteralDeclId)
deriving Repr, DecidableEq, BEq

inductive ClassOrigin where
  | expression (decl : ClassBodyDecl)
  | actor (decl : ClassBodyDecl)
deriving Repr, DecidableEq, BEq

inductive ScopeDecl where
  | classDecl (decl : ClassDeclId)
  | objectLiteralDecl (decl : ObjectLiteralDeclId)
  | activationDecl (decl : ActivationDeclId)
deriving Repr, DecidableEq, BEq

inductive SuperclassSyntax where
  | implicitSuperclass
  | explicitSuperclass
deriving Repr, DecidableEq, BEq

/-- Exact semantic payload of an atomic literal.  Character is deliberately
    absent, as required by Specification 0.109. -/
inductive AtomPayload where
  | integer (value : Int)
  | fixed (numerator : Int) (denominator : Nat)
  | boolean (value : Bool)
  | nilAtom
  | string (nfc : String)
  | symbol (nfc : String)
deriving Repr, DecidableEq, BEq

/-- A reified send request and the evaluated form of a deferred initializer
    message. -/
structure Message where
  selector : Selector
  arguments : List ObjRef
deriving Repr, DecidableEq, BEq

/-- Platform bindings used by syntax-directed library expansions. -/
inductive PlatformName where
  | readOnlyTuple
  | array
deriving Repr, DecidableEq, BEq

inductive ReflectRight where
  | inspect
  | editCode
  | editClass
  | reclassifyObject
  | editObjectSlots
  | editActivation
  | controlContinuation
  | controlActorStack
  | primitive
  | delegate
deriving Repr, DecidableEq, BEq

inductive MirrorTarget where
  | vmTarget (vm : VMId)
  | programTarget
  | mixinTarget (mixin : MixinId)
  | methodTarget (method : MethodId)
  | classTarget (classId : ClassId)
  | objectTarget (object : ObjRef)
  | activationTarget (activation : ActivationId)
  | actorTarget (actor : ActorId)
deriving Repr, DecidableEq, BEq

structure MirrorAuthority where
  vm : VMId
  target : MirrorTarget
  rights : List ReflectRight
deriving Repr, DecidableEq, BEq

/-- Static identities introduced when a cascade is elaborated to a one-argument
    closure.  `immediateClass` is absent precisely when the cascade occurs in
    top-level code. -/
structure CascadeDescriptor where
  closureDeclaration : ActivationDeclId
  receiverParameter : ParameterId
  receiverSelector : Selector
  immediateClass : Option ClassDeclId
deriving Repr

/- Executable core expressions and the recursively embedded pattern domain.
    Tuple nodes retain both their stable source site and the synthetic cascade
    descriptor generated by elaboration.  Pattern keyword nodes retain two
    such site/descriptor pairs, one for the ordered keyword symbols and one
    for their component patterns. -/
mutual
inductive CoreExpr where
  | value (object : ObjRef)
  | selfValue
  | ordinarySend (receiver : CoreExpr) (selector : Selector)
      (arguments : List CoreExpr)
  /-- Eventual send.  Receiver and arguments use the ordinary expression
      evaluator; the resulting eventual request is intercepted only by the
      actor semantics. -/
  | eventualSend (receiver : CoreExpr) (selector : Selector)
      (arguments : List CoreExpr)
  | implicitSend (selector : Selector) (arguments : List CoreExpr)
      (annotation : Option ScopeDecl) (immediate : Option ClassDeclId)
  | selfSend (selector : Selector) (arguments : List CoreExpr)
      (immediate : ClassDeclId)
  | outerSend (selector : Selector) (arguments : List CoreExpr)
      (target immediate : ClassDeclId)
  | superSend (selector : Selector) (arguments : List CoreExpr)
  | closureLiteral (declaration : ActivationDeclId)
  /-- A synthesized cascade closure whose clauses are already part of
      materialized control.  Reflective installation cannot rewrite them. -/
  | cascadeClosure (descriptor : CascadeDescriptor)
      (clauses : List (Selector × List CoreExpr))
  | readLocal (activation : ActivationId) (slot : LocalSlotId)
  | writeLocal (activation : ActivationId) (slot : LocalSlotId)
      (expression : CoreExpr)
  | classBody (declaration : ClassDeclId) (superclass : CoreExpr)
  | mixinApply (declaration : ClassDeclId) (superclass mixinSource : CoreExpr)
  | objectLiteral (declaration : ObjectLiteralDeclId) (superclass : CoreExpr)
  | atom (payload : AtomPayload)
  | tuple (site : SiteId) (cascade : CascadeDescriptor)
      (elements : List CoreExpr)
  | pattern (value : CorePattern) (annotation : Option ScopeDecl)
      (immediate : Option ClassDeclId)
  /-- A retained single-receiver cascade.  General source cascades elaborate
      away; this form is used by the dynamic tuple expansion and immediately
      expands to its statically identified closure. -/
  | cascade (descriptor : CascadeDescriptor) (receiver : CoreExpr)
      (clauses : List (Selector × List CoreExpr))
  | readSlot (object : ObjectId) (slot : SlotId)
  | writeSlot (object : ObjectId) (slot : SlotId) (expression : CoreExpr)
  | currentRead (slot : SlotId)
  | currentWrite (slot : SlotId) (expression : CoreExpr)
  | lazyRead (slot : SlotId) (initializer : CoreExpr)
  | nestedClass (declaration : ClassDeclId) (classExpression : CoreExpr)
  /-- Internal primary-factory primitive.  Its static syntax names the
      factory selector and formal parameters; their runtime values are read
      from the current factory activation. -/
  | newInstanceCurrent (selector : Selector) (parameters : List ParameterId)
deriving Repr

inductive CorePattern where
  | wildcard
  | literal (expression : CoreExpr)
  | variable (site : SiteId)
  | nested (value : CorePattern)
  | keyword (keywordTupleSite : SiteId)
      (keywordTupleCascade : CascadeDescriptor)
      (componentTupleSite : SiteId)
      (componentTupleCascade : CascadeDescriptor)
      (pairs : List (Selector × CorePattern))
deriving Repr
end

inductive LocalDeclaration where
  | immutable (slot : LocalSlotId) (initializer : CoreExpr)
  | mutableInitialized (slot : LocalSlotId) (initializer : CoreExpr)
  | mutableUninitialized (slot : LocalSlotId)
  | lazyImmutable (slot : LocalSlotId) (initializer : CoreExpr)
  | lazyMutable (slot : LocalSlotId) (initializer : CoreExpr)
deriving Repr

inductive LocalDeclarationGroup where
  | sequential (declaration : LocalDeclaration)
  | simultaneous (declarations : List LocalDeclaration)
deriving Repr

inductive Statement where
  | expression (value : CoreExpr)
  | return (value : CoreExpr)
deriving Repr

def cascadeReceiverReference (descriptor : CascadeDescriptor) : CoreExpr :=
  .implicitSend descriptor.receiverSelector []
    (some (.activationDecl descriptor.closureDeclaration))
    descriptor.immediateClass

def cascadeStatements (descriptor : CascadeDescriptor)
    (clauses : List (Selector × List CoreExpr)) : List Statement :=
  clauses.map fun clause =>
    .expression (.ordinarySend (cascadeReceiverReference descriptor)
      clause.1 clause.2)

def LocalDeclaration.slot : LocalDeclaration → LocalSlotId
  | .immutable slot _ => slot
  | .mutableInitialized slot _ => slot
  | .mutableUninitialized slot => slot
  | .lazyImmutable slot _ => slot
  | .lazyMutable slot _ => slot

def LocalDeclarationGroup.slots : LocalDeclarationGroup → List LocalSlotId
  | .sequential declaration => [declaration.slot]
  | .simultaneous declarations => declarations.map LocalDeclaration.slot

def localSlots (groups : List LocalDeclarationGroup) : List LocalSlotId :=
  groups.flatMap LocalDeclarationGroup.slots

structure MethodBody where
  sourceNode : Nat
deriving Repr, DecidableEq, BEq

structure MethodDef where
  identity : MethodId
  activationDeclaration : ActivationDeclId
  selector : Selector
  access : Access
  parameters : List ParameterId
  locals : List LocalSlotId
  owner : ClassBodyDecl
  body : MethodBody
deriving Repr, DecidableEq, BEq

/-- A deferred initializer message.  Its arguments are evaluated only when an
    instance is initialized, never while its class is constructed. -/
structure MessageTemplate where
  selector : Selector
  arguments : List CoreExpr
deriving Repr

inductive SlotDeclaration where
  | immutable (slot : SlotId) (initializer : CoreExpr)
      (futureThunk : ActivationDeclId)
  | mutableInitialized (slot : SlotId) (initializer : CoreExpr)
      (futureThunk : ActivationDeclId)
  | mutableUninitialized (slot : SlotId)
deriving Repr

inductive SlotDeclarationGroup where
  | sequential (declarations : List SlotDeclaration)
  | simultaneous (declarations : List SlotDeclaration)
deriving Repr

def SlotDeclaration.slot : SlotDeclaration → SlotId
  | .immutable slot _ _ => slot
  | .mutableInitialized slot _ _ => slot
  | .mutableUninitialized slot => slot

def SlotDeclarationGroup.slots : SlotDeclarationGroup → List SlotId
  | .sequential declarations => declarations.map SlotDeclaration.slot
  | .simultaneous declarations => declarations.map SlotDeclaration.slot

inductive ClassOwner where
  | activationOwner
  | classOwner
  | objectLiteralOwner
  | topOwner
deriving Repr, DecidableEq, BEq

/-- Static data attached by elaboration to a normalized class body. -/
structure ClassBodyDescriptor where
  declaration : ClassDeclId
  superclassSyntax : SuperclassSyntax
  factorySelector : Selector
  factoryParameters : List ParameterId
  instanceMixin : MixinId
  classMixin : MixinId
  initializerDeclaration : ActivationDeclId
  superclassMessage : MessageTemplate
deriving Repr

/-- Static data attached to a normalized mixin application. -/
structure MixinApplicationDescriptor where
  declaration : ClassDeclId
  factorySelector : Selector
  factoryParameters : List ParameterId
  classMixin : MixinId
  initializerDeclaration : ActivationDeclId
  superclassMessage : MessageTemplate
  mixinMessage : MessageTemplate
deriving Repr

/-- Static data attached to an object literal.  The instance mixin is shared
    by all evaluations; the implicit class and its metaclass are not. -/
structure ObjectLiteralDescriptor where
  declaration : ObjectLiteralDeclId
  superclassSyntax : SuperclassSyntax
  instanceMixin : MixinId
  classMixin : MixinId
  initializerDeclaration : ActivationDeclId
  superclassMessage : MessageTemplate
deriving Repr

/-- Static seed retained for the actor-spawn primitive.  The instance mixin
    is the key in `Program.actorSeeds`; the remaining fields construct the
    fresh actor class and its primary factory. -/
structure ActorSeedDescriptor where
  declaration : ClassDeclId
  classMixin : MixinId
  factorySelector : Selector
  factoryParameters : List ParameterId
  initializerDeclaration : ActivationDeclId
  superclassMessage : MessageTemplate
deriving Repr

end Newspeak
