#!/bin/sh -x

# 1. Read utility functions and ensure (heuristically) directory is tool
if [ ! -f ./newspeak_util.sh ]; then printf "\n\nERROR: Run this command from Newspeak 'tool' directory. Current directory=%s. Exiting.\n\n" "$PWD"; exit 1; fi
. ./newspeak_util.sh
set -o errexit
check_dir_is_tool

# 2. If additional arguments are provided, they are assumed to be 3-tuples to compile.
# For example, if users want to build vfuel for 'CheckedItemApp.ns',
# they could provide build arguments as follows:
#   ./build.sh RuntimeForHopscotchForHTML CheckedItemApp CheckedItemApp.vfuel
additionalNs="$*"

# 3. Setup the emscripten environment needed to build primordialsoup.
# Emscripten must be installed in the $EMSDK directory, set in 'newspeak_env.sh'.
# To install emscripten and configure the version to use,
#   see https://github.com/newspeaklanguage/primordialsoup/blob/master/docs/building.md
# Emscripten 'latest' and '2.0.0' are tested
# In summary, to configure emscripten version:
#   - cd $EMSDK
#   - ./emsdk install  latest # or 2.0.0 instead of 'latest'
#   - ./emsdk activate latest # or 2.0.0 instead of 'latest'
# shellcheck source=/dev/null
. ${EMSDK}/emsdk_env.sh

# 4. Build primordialsoup from it's directory.
cd ${PRIMORDIALSOUP} || exit 1
./build os=emscripten arch=wasm

# 4a. Build NewspeakParser.vfuel for parse-validate.sh script
./out/ReleaseX64/primordialsoup \
  ./out/snapshots/WebCompiler.vfuel \
  ./newspeak/*.ns \
  ${NEWSPEAK}/NewspeakParser.ns \
  RuntimeWithMirrorsForPrimordialSoup NewspeakParser ./out/snapshots/NewspeakParser.vfuel

# 4b. Build NewspeakTestRunner.vfuel for run-tests.sh script
./out/ReleaseX64/primordialsoup \
  ./out/snapshots/WebCompiler.vfuel \
  ./newspeak/*.ns \
  ${NEWSPEAK}/NewspeakTestRunner.ns \
  RuntimeWithMirrorsForPrimordialSoup NewspeakTestRunner ./out/snapshots/NewspeakTestRunner.vfuel

# 4c. Build NewspeakPrettyPrintApp.vfuel for tool/pretty-print.sh script
./out/ReleaseX64/primordialsoup \
  ./out/snapshots/WebCompiler.vfuel \
  ./newspeak/*.ns \
  ${NEWSPEAK}/NewspeakASTs.ns \
  ${NEWSPEAK}/NewspeakPrettyPrinter.ns \
  ${NEWSPEAK}/NewspeakPrettyPrintApp.ns \
  RuntimeWithMirrorsForPrimordialSoup NewspeakPrettyPrintApp ./out/snapshots/NewspeakPrettyPrintApp.vfuel

# 4d. Build NewspeakRoundTripCheckApp.vfuel for tool/round-trip-check.sh script
./out/ReleaseX64/primordialsoup \
  ./out/snapshots/WebCompiler.vfuel \
  ./newspeak/*.ns \
  ${NEWSPEAK}/NewspeakASTs.ns \
  ${NEWSPEAK}/NewspeakPrettyPrinter.ns \
  ${NEWSPEAK}/NewspeakRoundTripCheckApp.ns \
  RuntimeWithMirrorsForPrimordialSoup NewspeakRoundTripCheckApp ./out/snapshots/NewspeakRoundTripCheckApp.vfuel

# Back to 'newspeak'.
cd ${NEWSPEAK} || exit 1

# 4e. Stamp BuildInfo.ns with the real, git-derived version for this build.
#     The committed BuildInfo.ns is a placeholder ('development build'); we
#     overwrite it here so the compiled vfuel reports its true provenance, then
#     restore the placeholder after the compile (step 8) to keep the tree clean.
#     The dirty flag is computed BEFORE the rewrite so the regen isn't self-counted.
IDE_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
IDE_DATE=$(git show -s --format=%cs HEAD 2>/dev/null || echo unknown)
VM_SHA=$(git -C ${PRIMORDIALSOUP} rev-parse --short HEAD 2>/dev/null || echo unknown)
# Tracked changes only (--untracked-files=no): scratch .md/.zip/etc. left in the
# tree shouldn't flag a build as dirty -- only uncommitted edits to tracked files do.
test -n "$(git status --porcelain --untracked-files=no 2>/dev/null)" && DIRTY=' (dirty)' || DIRTY=''
BUILT=$(date -u +%Y-%m-%dT%H:%MZ)
cat > BuildInfo.ns <<NSEOF
Newspeak3
'Root'
class BuildInfo packageUsing: manifest = Object new (
	(* Build/version stamp -- GENERATED by tool/build.sh for this build; the
	committed copy is a 'development build' placeholder. Do not commit the
	stamped form. *)
) (
) : (
	public version = (
		^'${IDE_SHA} ${IDE_DATE}, VM ${VM_SHA}, built ${BUILT}${DIRTY}'
	)
)
NSEOF

# 5. Ensure the newspeak/out directory exists, and copy into it:
#   - The primordialsoup built primordialsoup.html, primordialsoup.js, primordialsoup.wasm
#   - All primordialsoup built snapshots of vfuel files such as WebCompiler.vfuel
#   - Note that primordialsoup.* have a copy in primordialsoup repo and multiple
#     copies in the newspeak repo. Deployments use the versions from the primordialsoup repo.
mkdir -p out
cp ${PRIMORDIALSOUP}/out/ReleaseEmscriptenWASM/primordialsoup.* out
cp ${PRIMORDIALSOUP}/out/snapshots/*.vfuel out
# 6. Copy Psoup Newspeak code
cp ${PRIMORDIALSOUP}/newspeak/*.ns out
# 7. Merge in Newspeak IDE dependencies
cp ./*.ns ./*.png out
# deploy-boot.js: shared boot for web-deployed Ampleforth documents (see
# Documents>>deployForWeb:). Lean deployed pages reference it; it replays the
# real primordialsoup.html loader at runtime. Served from out/ and mirrored to
# deploy targets by the deploy scripts.
cp ./deploy-boot.js out
# cp -R CodeMirror out # CodeMirror is copied during deploy

# 7a. Stage self-hosted third-party JS (isomorphic-git, lightning-fs).
# Vendored under vendor/ at the repo root and consumed by the deploy
# scripts. Mirror the whole dir so additions land automatically.
mkdir -p out/vendor
cp ./vendor/*.js out/vendor/

cd ${NEWSPEAK}/out || exit 1

# ${PRIMORDIALSOUP}/out/ReleaseX64/primordialsoup \
#     ${PRIMORDIALSOUP}/primordialsoup/out/snapshots/WebCompiler.vfuel \
#     *.ns \
#     *.png \
# not in 'out':    *.txt \
# not needed, included in html both index.html for WebIDE and primordialsoup.html:    CodeMirror/lib/codemirror.js \
# not needed, included in html both index.html for WebIDE and primordialsoup.html:    CodeMirror/addon/display/autorefresh.js \
#     RuntimeForHopscotchForHTML HopscotchWebIDE HopscotchWebIDE.vfuel \
#     RuntimeForElectron HopscotchWebIDE HopscotchElectronIDE.vfuel \
#     RuntimeForHopscotchForHTML Ampleforth Ampleforth.vfuel  \
#     RuntimeForHopscotchForHTML AmpleforthViewer AmpleforthViewer.vfuel  \
# not in git:   RuntimeForHopscotchForHTML Live22Submission Live22Submission.vfuel  \
# not in git:   RuntimeForHopscotchForHTML Smalltalks22Tutorial Smalltalks22.vfuel  \
# not in git:   RuntimeForHopscotchForHTML Live22Presentation Live22Presentation.vfuel  \
#     RuntimeForCroquet CounterApp CroquetCounterApp.vfuel \
#     RuntimeForHopscotchForHTML CounterApp CounterApp.vfuel \
#     RuntimeForHopscotchForHTML TodoMVCApp TodoMVCApp.vfuel \
#     RuntimeForCroquet TodoMVCApp CroquetTodoMVCApp.vfuel \
#     RuntimeForHopscotchForHTML TwoViewEditorApp TwoViewEditorApp.vfuel \
#     RuntimeForHopscotchForHTML TelescreenApp Telescreen.vfuel \
#     RuntimeForHopscotchForHTML ObjectPresenterDemo ObjectPresenterDemo.vfuel \
#     RuntimeForHopscotchForHTML BankAccountExemplarDemo BankAccountExemplarDemo.vfuel \
#     RuntimeForHopscotchForHTML HopscotchFontDemo HopscotchFontDemo.vfuel \
#     RuntimeForHopscotchForHTML HopscotchGestureDemo HopscotchGestureDemo.vfuel \
#     RuntimeForHopscotchForHTML HopscotchDemo HopscotchDemo.vfuel \
#     RuntimeForHopscotchForHTML Particles Particles.vfuel

#
# 8. Create vfuel files (ex: HopscotchWebIDE.vfuel)
#    from ns files (ex: HopscotchWebIDE.ns) and
#    additional resources (*.ns, *.png).
#
${PRIMORDIALSOUP}/out/ReleaseX64/primordialsoup \
    ${PRIMORDIALSOUP}/out/snapshots/WebCompiler.vfuel \
    ./*.ns \
    ./*.png \
    RuntimeForHopscotchForHTML HopscotchWebIDE HopscotchWebIDE.vfuel \
    RuntimeForHopscotchForHTML Ampleforth Ampleforth.vfuel  \
    RuntimeForHopscotchForHTML AmpleforthViewer AmpleforthViewer.vfuel  \
    RuntimeForCroquet CounterApp CroquetCounterApp.vfuel \
    RuntimeForHopscotchForHTML CounterApp CounterApp.vfuel \
    RuntimeForHopscotchForHTML TodoMVCApp TodoMVCApp.vfuel \
    RuntimeForCroquet TodoMVCApp CroquetTodoMVCApp.vfuel \
    RuntimeForHopscotchForHTML TwoViewEditorApp TwoViewEditorApp.vfuel \
    RuntimeForHopscotchForHTML TelescreenApp Telescreen.vfuel \
    RuntimeForHopscotchForHTML ObjectPresenterDemo ObjectPresenterDemo.vfuel \
    RuntimeForHopscotchForHTML BankAccountExemplarDemo BankAccountExemplarDemo.vfuel \
    RuntimeForHopscotchForHTML HopscotchFontDemo HopscotchFontDemo.vfuel \
    RuntimeForHopscotchForHTML HopscotchGestureDemo HopscotchGestureDemo.vfuel \
    RuntimeForHopscotchForHTML HopscotchDemo HopscotchDemo.vfuel \
    RuntimeForHopscotchForHTML Particles Particles.vfuel \
    "$additionalNs"

# Restore the committed BuildInfo.ns placeholder (it was stamped for this build
# only, in step 4e). Tolerant of a not-yet-tracked file on a first build.
( cd ${NEWSPEAK} && git checkout -- BuildInfo.ns 2>/dev/null ) || true

cd ${NEWSPEAK}/tool || exit 1
